-- Migration 013: PostGIS foundation
-- Installs PostGIS, creates order_delivery_snapshots, extends address tables
-- with geography columns and sync triggers for spatial queries.
-- Safe to re-run: all DDL uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ── 1. Enable PostGIS ─────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS postgis;


-- ── 2. Shared trigger: keep .location in sync from latitude + longitude ────────
-- Used by tables whose location column tracks a lat/lon pair named exactly
-- "latitude" and "longitude".
CREATE OR REPLACE FUNCTION public.sync_latlong_to_geography()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
        NEW.location := ST_SetSRID(
            ST_MakePoint(NEW.longitude::double precision, NEW.latitude::double precision),
            4326
        )::geography;
    ELSE
        NEW.location := NULL;
    END IF;
    RETURN NEW;
END;
$$;


-- ── 3. order_delivery_snapshots ───────────────────────────────────────────────
-- Stores a per-order delivery address snapshot that can be updated without
-- changing the customer's permanent profile. Supports pre- and post-dispatch
-- emergency updates with driver acknowledgement workflow.
CREATE TABLE IF NOT EXISTS public.order_delivery_snapshots (
    snapshot_id            bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id               bigint                      NOT NULL,
    contact_name           character varying(100),
    contact_mobile         character varying(20),
    alternate_mobile       character varying(20),
    address_line1          character varying(255),
    address_line2          character varying(255),
    city                   character varying(100),
    state                  character varying(100),
    country                character varying(100),
    postal_code            character varying(20),
    landmark               character varying(255),
    delivery_instructions  text,
    latitude               numeric(10,7),
    longitude              numeric(10,7),
    location               geography(Point, 4326),
    gps_accuracy_meters    numeric(8,2),
    location_source        character varying(50),
    confirmed_by           bigint,
    confirmed_at           timestamp without time zone,
    emergency_updated      boolean                     DEFAULT false NOT NULL,
    requires_driver_ack    boolean                     DEFAULT false NOT NULL,
    driver_acknowledged_by bigint,
    driver_acknowledged_at timestamp without time zone,
    created_at             timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at             timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT order_delivery_snapshots_pkey PRIMARY KEY (snapshot_id),
    CONSTRAINT order_delivery_snapshots_order_id_key UNIQUE (order_id),
    CONSTRAINT order_delivery_snapshots_order_id_fkey
        FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ods_order_id
    ON public.order_delivery_snapshots (order_id);

CREATE INDEX IF NOT EXISTS idx_ods_location
    ON public.order_delivery_snapshots USING GIST (location)
    WHERE location IS NOT NULL;

-- Sync trigger for order_delivery_snapshots
DROP TRIGGER IF EXISTS trg_ods_sync_location ON public.order_delivery_snapshots;
CREATE TRIGGER trg_ods_sync_location
    BEFORE INSERT OR UPDATE OF latitude, longitude
    ON public.order_delivery_snapshots
    FOR EACH ROW EXECUTE FUNCTION public.sync_latlong_to_geography();


-- ── 4. user_addresses: extend with landmark + GPS metadata + geography ─────────
ALTER TABLE public.user_addresses
    ADD COLUMN IF NOT EXISTS landmark            character varying(255),
    ADD COLUMN IF NOT EXISTS gps_accuracy_meters numeric(8,2),
    ADD COLUMN IF NOT EXISTS location_source     character varying(50),
    ADD COLUMN IF NOT EXISTS location            geography(Point, 4326);

-- Back-fill geography for any rows that already have coordinates
UPDATE public.user_addresses
    SET location = ST_SetSRID(
        ST_MakePoint(longitude::double precision, latitude::double precision),
        4326
    )::geography
    WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND location IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_addresses_location
    ON public.user_addresses USING GIST (location)
    WHERE location IS NOT NULL;

DROP TRIGGER IF EXISTS trg_user_addresses_sync_location ON public.user_addresses;
CREATE TRIGGER trg_user_addresses_sync_location
    BEFORE INSERT OR UPDATE OF latitude, longitude
    ON public.user_addresses
    FOR EACH ROW EXECUTE FUNCTION public.sync_latlong_to_geography();


-- ── 5. nursery_addresses: extend with landmark + GPS metadata + geography ──────
ALTER TABLE public.nursery_addresses
    ADD COLUMN IF NOT EXISTS landmark            character varying(255),
    ADD COLUMN IF NOT EXISTS gps_accuracy_meters numeric(8,2),
    ADD COLUMN IF NOT EXISTS location_source     character varying(50),
    ADD COLUMN IF NOT EXISTS location            geography(Point, 4326);

UPDATE public.nursery_addresses
    SET location = ST_SetSRID(
        ST_MakePoint(longitude::double precision, latitude::double precision),
        4326
    )::geography
    WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND location IS NULL;

CREATE INDEX IF NOT EXISTS idx_nursery_addresses_location
    ON public.nursery_addresses USING GIST (location)
    WHERE location IS NOT NULL;

DROP TRIGGER IF EXISTS trg_nursery_addresses_sync_location ON public.nursery_addresses;
CREATE TRIGGER trg_nursery_addresses_sync_location
    BEFORE INSERT OR UPDATE OF latitude, longitude
    ON public.nursery_addresses
    FOR EACH ROW EXECUTE FUNCTION public.sync_latlong_to_geography();


-- ── 6. driver_locations: add geography column ──────────────────────────────────
ALTER TABLE public.driver_locations
    ADD COLUMN IF NOT EXISTS location geography(Point, 4326);

UPDATE public.driver_locations
    SET location = ST_SetSRID(
        ST_MakePoint(longitude::double precision, latitude::double precision),
        4326
    )::geography
    WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND location IS NULL;

CREATE INDEX IF NOT EXISTS idx_driver_locations_location
    ON public.driver_locations USING GIST (location)
    WHERE location IS NOT NULL;

-- driver_locations.latitude/longitude are NOT NULL, so location is always set
DROP TRIGGER IF EXISTS trg_driver_locations_sync_location ON public.driver_locations;
CREATE TRIGGER trg_driver_locations_sync_location
    BEFORE INSERT OR UPDATE OF latitude, longitude
    ON public.driver_locations
    FOR EACH ROW EXECUTE FUNCTION public.sync_latlong_to_geography();
